name: gh-pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: deploy to gh pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Run install
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install --frozen-lockfile # will run `yarn install` command
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: predeploy # will run `yarn predeploy` command
        env:
          PUBLIC_URL: "https://mmncit.github.io/dpatterna"

      - name: Build and deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: public